import Plus from '../assets/images/plus.svg';
import Play from '../assets/images/play.svg';
import Pause from '../assets/images/pause.svg';
import Prev from '../assets/images/prev.svg';
import Next from '../assets/images/next.svg';
import Close from '../assets/images/close.svg';
import Check from '../assets/images/check.svg';
import Mic from '../assets/images/mic.svg';
import StopRec from '../assets/images/stop-rec.svg';
import Edit from '../assets/images/edit.svg';
import AddList from '../assets/images/add-list.svg';
import ChevronDown from '../assets/images/chevron-down.svg';
import List from '../assets/images/list.svg';
import Settings from '../assets/images/settings.svg';
import Shuffle from '../assets/images/shuffle.svg';
import ForwardBack from '../assets/images/forward-back.svg';
import ForwardFront from '../assets/images/forward-front.svg';
import Repeat from '../assets/images/repeat.svg';
import Queue from '../assets/images/queue.svg';
import Arrow from '../assets/images/arrow.svg';
import Minus from '../assets/images/minus.svg';

export const Icons = {
  Plus: () => Plus,
  Play: () => Play,
  Pause: () => Pause,
  Prev: () => Prev,
  Next: () => Next,
  Close: () => Close,
  Check: () => Check,
  Mic: () => Mic,
  StopRec: () => StopRec,
  Edit: () => Edit,
  AddList: () => AddList,
  ChevronDown: () => ChevronDown,
  List: () => List,
  Settings: () => Settings,
  Shuffle: () => Shuffle,
  ForwardBack: () => ForwardBack,
  ForwardFront: () => ForwardFront,
  Repeat: () => Repeat,
  Queue: () => Queue,
  Arrow: () => Arrow,
  Minus: () => Minus,
};
