export const ENGLISH_GROUP = {
  'Recording is in progress': 'Recording is in progress.',
  'Click on the Circle icon to finish': 'Click on the Circle icon to finish.',
  'Please fill all the required fields': 'Please, fill all the required fields.',
  'They are marked with the sign': 'They are marked with the "*" sign.',
  'Word List': 'Word List',
  'All Lists': 'All Lists',
  'Not connected items': 'Not connected items',
  'All items': 'All items',
  'New List': 'New List',
  'New Word': 'New Word',
  'Foreign Audio': 'Foreign Audio',
  'Contained Lists': 'Add to the lists',
  'Timer to stop player': 'Timer to stop player:',
  'Settings': 'Settings',
  'Foreign sentence': 'Foreign sentence',
  'delay between the audios': 'delay between the audios',
  'List is empty Add a new word': 'List is empty. Add a new word.',
  'Translation': 'Translation',
  'Edit Word': 'Edit Word',
  'Name': 'Name',
  'Description': 'Description',
  'Add one more': 'Add one more',
};

export const RUSSIAN_GROUP = {
  'Recording is in progress': 'Идет запись.',
  'Click on the Circle icon to finish': 'Нажмите на кружок чтобы закончить.',
  'Please fill all the required fields': 'Пожалуйста, заполните все необходимые поля.',
  'They are marked with the sign': 'Они помечены знаком "*" .',
  'Word List': 'Список слов',
  'All Lists': 'Все Списки',
  'Not connected items': 'Непривязанные слова',
  'All items': 'Все слова',
  'New List': 'Новый Список',
  'New Word': 'Новое Слово',
  'Foreign Audio': 'Иностранное Аудио',
  'Contained Lists': 'Добавить в списки',
  'Timer to stop player': 'Таймер для остановки плеера:',
  'Settings': 'Настройки',
  'Foreign sentence': 'Иностранное предложение',
  'delay between the audios': 'задержка между аудиозаписями',
  'List is empty Add a new word': 'Список пуст. Добавить новое слово.',
  'Translation': 'Перевод',
  'Edit Word': 'Редактировать Слово',
  'Name': 'Имя',
  'Description': 'Описание',
  'Add one more': 'Добавить еще',
};

export const POLISH_GROUP = {
  'Recording is in progress': 'Trwa nagrywanie.',
  'Click on the Circle icon to finish': 'Kliknij kółko, aby zakończyć.',
  'Please fill all the required fields': 'Proszę wypełnić wszystkie wymagane pola.',
  'They are marked with the sign': 'Są oznaczone znakiem "*".',
  'Word List': 'Lista Słów',
  'All Lists': 'Wszystkie Listy',
  'Not connected items': 'Nie podłączone elementy',
  'All items': 'Wszystkie pozycje',
  'New List': 'Nowa Lista',
  'New Word': 'Nowe Słowo',
  'Foreign Audio': 'Zagraniczne Audio',
  'Contained Lists': 'Zawarte Listy',
  'Timer to stop player': 'Timer do zatrzymania gracza:',
  'Settings': 'Ustawienia',
  'Foreign sentence': 'Wyrok zagraniczny',
  'delay between the audios': 'opóźnienie między dźwiękami',
  'List is empty Add a new word': 'Lista jest pusta. Dodaj nowe słowo.',
  'Translation': 'Tłumaczenie',
  'Edit Word': 'Edytuj Słowo',
  'Name': 'Nazwa',
  'Description': 'Opis',
  'Add one more': 'Dodaj jeszcze jedną',
};

export const ITALIAN_GROUP = {
  'Recording is in progress': 'La registrazione è in corso.',
  'Click on the Circle icon to finish': 'Fare clic sull\'icona del cerchio per finire.',
  'Please fill all the required fields': 'Si prega di compilare tutti i campi richiesti.',
  'They are marked with the sign': 'Sono contrassegnati con il segno"*".',
  'Word List': 'Elenco di Parole',
  'All Lists': 'Tutte le Liste',
  'Not connected items': 'Elementi non collegati',
  'All items': 'Tutti gli articoli',
  'New List': 'Nuovo Elenco',
  'New Word': 'Nuova Parola',
  'Foreign Audio': 'Audio Straniero',
  'Contained Lists': 'Elenchi Contenuti',
  'Timer to stop player': 'Timer per fermare il giocatore:',
  'Settings': 'Impostazioni',
  'Foreign sentence': 'Sentenza straniera',
  'delay between the audios': 'ritardo tra gli audio',
  'List is empty Add a new word': 'La lista è vuota. Aggiungi una nuova parola.',
  'Translation': 'Traduzione',
  'Edit Word': 'Modifica Parola',
  'Name': 'Nome',
  'Description': 'Descrizione',
  'Add one more': 'Aggiungi un altro',
};

export const GERMAN_GROUP = {
  'Recording is in progress': 'Die Aufnahme ist im Gange.',
  'Click on the Circle icon to finish': 'Klicken Sie zum Beenden auf das Kreissymbol.',
  'Please fill all the required fields': 'Bitte füllen Sie alle erforderlichen Felder aus.',
  'They are marked with the sign': 'Sie sind mit dem Zeichen "*" gekennzeichnet.',
  'Word List': 'Wortliste',
  'All Lists': 'Alle Listen',
  'Not connected items': 'Nicht verbundene Gegenstände',
  'All items': 'Alle Artikel',
  'New List': 'Neue Liste',
  'New Word': 'Neues Wort',
  'Foreign Audio': 'Ausländische Audio',
  'Contained Lists': 'Enthaltene Listen',
  'Timer to stop player': 'Timer zum Stoppen des Players:',
  'Settings': 'Einstellung',
  'Foreign sentence': 'Ausländischer Satz',
  'delay between the audios': 'Verzögerung zwischen den audios',
  'List is empty Add a new word': 'Liste ist leer. Fügen Sie ein neues Wort hinzu.',
  'Translation': 'Übersetzung',
  'Edit Word': 'Wort bearbeiten',
  'Name': 'Name',
  'Description': 'Beschreibung',
  'Add one more': 'Fügen Sie eine weitere hinzu',
};

export const SPANISH_GROUP = {
  'Recording is in progress': 'La grabación está en curso.',
  'Click on the Circle icon to finish': 'Haga clic en el icono del círculo para terminar.',
  'Please fill all the required fields': 'Por favor, rellene todos los campos requeridos.',
  'They are marked with the sign': 'Están marcados con el signo "*".',
  'Word List': 'Lista de Palabras',
  'All Lists': 'Todas las Listas',
  'Not connected items': 'Elementos no conectados',
  'All items': 'Todos los artículos',
  'New List': 'Nueva Lista',
  'New Word': 'Palabra Nueva',
  'Foreign Audio': 'Audio Extranjero',
  'Contained Lists': 'Listas Contenidas',
  'Timer to stop player': 'Temporizador para detener al jugador:',
  'Settings': 'Configuración',
  'Foreign sentence': 'Sentencia extranjera',
  'delay between the audios': 'retardo entre los audios',
  'List is empty Add a new word': 'La lista está vacía. Añade una nueva palabra.',
  'Translation': 'Traducción',
  'Edit Word': 'Editar Palabra',
  'Name': 'Nombre',
  'Description': 'Descripci',
  'Add one more': 'Añadir uno más',
};

export const FRENCH_GROUP = {
  'Recording is in progress': 'L\'enregistrement est en cours.',
  'Click on the Circle icon to finish': 'Cliquez sur l\'icône du cercle pour terminer.',
  'Please fill all the required fields': 'Veuillez remplir tous les champs requis.',
  'They are marked with the sign': 'Ils sont marqués avec le signe"*".',
  'Word List': 'Liste de Mots',
  'All Lists': 'Toutes Les Listes',
  'Not connected items': 'Articles non connectés',
  'All items': 'Tous les articles',
  'New List': 'Nouvelle Liste',
  'New Word': 'Nouveau Mot',
  'Foreign Audio': 'Étrangères Audio',
  'Contained Lists': 'Contenait Des Listes',
  'Timer to stop player': 'Minuterie pour arrêter le joueur:',
  'Settings': 'Paramètre',
  'Foreign sentence': 'Étrangères phrase',
  'delay between the audios': 'délai entre les audios',
  'List is empty Add a new word': 'La liste est vide. Ajouter un nouveau mot.',
  'Translation': 'Traduction',
  'Edit Word': 'Modifier le Mot',
  'Name': 'Nom',
  'Description': 'Description',
  'Add one more': 'Ajouter un de plus',
};
